name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  qualification:
    name: Complete beta qualification
    permissions:
      actions: read
      contents: read
    uses: ./.github/workflows/qualification.yml
